trigger:
  branches:
    include:
     - feature
     - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'DockerRegistry'  # Replace with your Docker registry service connection name

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      displayName: 'Maven Build'

    # - task: Docker@2
    #   displayName: 'Build and Push Docker Image'
    #   inputs:
    #     containerRegistry: $(dockerRegistryServiceConnection)
    #     repository: 'riaoct30/tomcat-test'
    #     command: 'buildAndPush'
    #     Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    - task: Docker@2
      displayName: Docker Build&Push
      inputs:
        containerRegistry: 'Contregsanga'
        repository: 'tomcat-test'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
      retryCountOnTaskFailure: 3
