# trigger:
#   branches:
#     include:
#      - feature
#      - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'DockerRegistry'  # Replace with your Docker registry service connection name
  imageRepository: 'tomcat-test'
  namespace: 'sanghamitra'
  k8sdeployment: 'deployment.yaml'
  DOCKER_HUB_USER: 'riaoct30'
  DOCKER_HUB_PAT: 'docker@ria30'

  
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Default
    steps:
#############################

# Packaging the Code

#############################
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      displayName: 'Maven Build'

#############################

# Build and Push Image to DockerHub
 
# #############################
#     - task: Docker@2
#       displayName: 'Build and Push Docker Image'
#       inputs:
#         containerRegistry: $(dockerRegistryServiceConnection)
#         repository: 'riaoct30/$(imageRepository)'
#         command: 'buildAndPush'
#         Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#         tags: |
#           $(tag)


#############################

# Build Docker Image
 
#############################

    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        containerRegistry: 'DockerRegistry'
        repository: 'riaoct30/$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tag: |
          $(tag)

#############################

# Scan Docker Image using Docker Scout
 
#############################
    
    - task: CmdLine@2
      displayName: ImageScan after Build
      inputs:
        script: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
          # docker login -u $(DOCKER_HUB_USER) -p $(DOCKER_HUB_PAT)
          docker scout cves riaoct30/$(imageRepository):$(tag) --exit-code --only-severity critical,high 

#############################

# Push to Docker Hub
 
#############################
    - task: Docker@2
      displayName: 'Pushing to DockerHub'
      inputs:
        containerRegistry: 'DockerRegistry'
        repository: 'riaoct30/$(imageRepository)'
        command: 'push'
        tags: |
          $(tag)

#############################

# Scan Docker Image using Docker Scout
 
#############################
    
    - task: CmdLine@2
      displayName: Image Scan after Push
      inputs:
        script: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s --
          docker login -u $(DOCKER_HUB_USER) -p $(DOCKER_HUB_PAT)
          docker scout cves riaoct30/$(imageRepository):$(tag) --exit-code --only-severity critical,high

#############################

# Build and Push Image to ACR
 
#############################
    # - task: Docker@2
    #   displayName: Docker Build&Push
    #   inputs:
    #     containerRegistry: 'Contregsanga'
    #     repository: $(imageRepository)
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
      # retryCountOnTaskFailure: 3
    
#############################

# Kubectl Installer
 
#############################
    - task: KubectlInstaller@0
      displayName: 'Install Kubectl'
      inputs:
        kubectlVersion: 'latest'

#############################

# Copy Files into Agent

#############################
    - task: CopyFiles@2
      displayName: 'Copy Files to Agent'
      inputs:
        Contents: $(k8sdeployment)
        TargetFolder: '$(build.artifactstagingdirectory)'

#############################

# Publish Build Artifact

#############################
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
#############################

# Deploy to AKS Cluster

#############################
    - task: KubernetesManifest@1
      displayName: 'Deploy to AKS'
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'kubeclust'
        namespace: $(namespace)
        strategy: 'canary'
        percentage: '0'
        manifests: $(k8sdeployment)
      
#############################

# Kubectl Apply

#############################
    - task: Kubernetes@1
      displayName: 'Apply Deployments'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'kubeclust'
        namespace: $(namespace)
        command: 'apply'
        useConfigurationFile: true
        configuration: $(k8sdeployment)
        secretType: 'dockerRegistry'
        containerRegistryType: 'Container Registry'


#############################

# Show External IP:PORT
 
#############################
    - task: Kubernetes@1
      displayName: 'ExternalIP and Port'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'kubeclust'
        namespace: '$(namespace)'
        command: 'get'
        arguments: 'svc'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Container Registry'
