apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: flux-system-sanga
spec:
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfod
          image: riaoct30/tomcat-test
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
