apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: podinfo
  namespace: sanghamitra-nm
spec:
  imageRepositoryRef:
    name: podinfo
  policy:
    semver:
      range: 1.0.x